#!/bin/bash
cd build
rm -rf *
cmake ../
make
sudo make install
cd ..
cd dname
make clean
make




echo
echo
echo
echo "********************************************************************************"
./dname $@
echo "********************************************************************************"
echo
echo
echo
